### ISSUE TITLE
Add layer bugs

### ISSUE THREAD

**Issue by offbit** [liuzhuang13/DenseNet#1]
Hi, 

check out the code at 

https://github.com/liuzhuang13/DenseNet/blob/master/densenet.lua#L54

param requires nOutChannels, but you pass growth rate. 

Also add layer only adds direct connection to the next layer,  so you form n-1 connections, as far as I understood from your paper it should have n-2, n-3 , etc... for every layer in the block. 
I'm guessing this is not the version you used to train the models. 

Thanks for sharing.

**Comment by liuzhuang13** [comment]
Thanks for opening this issue. The function addLayer does require nOutChannels, and for each layer this param means the newly learned feature maps at thsi layer, which equal to growth rate. Maybe I'll change this param's name to be growth rate. 

Superficially, there's only n-1 connections, but in function addLayer, every time the new feature maps learned by this layer, **concated with all previous feature maps**, are passed to subsequent layers, through the use of nn.Concat() and nn.Identity(). It's equivalent to the connection pattern described in paper. Identity mapping connections are for ease of implementation, one can also keep a set of each layer's feature maps and every time first concate them then do convolution, but that's a little more compilcated to implement.

**Comment by offbit** [comment]
Excellent :) 
I think I didn't pay much attention, and had in mind the residual connection type. But yes, concat makes perfect sense! 

Thanks for the clarifications.
