### ISSUE TITLE
./checkpoints.lua:52: attempt to call method 'clearState' (a nil value)

### ISSUE THREAD

**Issue by pannous** [liuzhuang13/DenseNet#2]
1) Great work, a milestone! Never seen top5 go down so seamlessly.

2) little bug:
```
th main.lua -netType densenet -depth 40 -dataset cifar10 -batchSize 64 -nEpochs 300 -optnet true
...
 | Test: [1][157/157]    Time 0.021  Data 0.000  top1  87.500 ( 83.420)  top5  50.000 ( 55.870)	
 * Finished epoch # 1     top1:  83.420  top5:  55.870
 * Best model 	83.42	55.87	

./checkpoints.lua:52: attempt to call method 'clearState' (a nil value)

```

**Comment by pannous** [comment]
seems to be caused by -optnet true

**Comment by liuzhuang13** [comment]
Yeah we recommend to install optnet first. 

We haven't see bugs about the method 'clearState', this method was written by fb.resnet.torch. Check if you can train resnet using fb.resnet.torch.

In our experiment with DenseNet (L=40, k=12), the error rate on CIFAR-10+ after one epoch is typically ~50%, so there might be some other bugs.

Thanks

**Comment by pannous** [comment]
> error rate on CIFAR-10+ after one epoch is typically ~50%
oh, we're on CIFAR-100, so that's ok

> written by fb.resnet.torch
ok, thanks anyways

( optnet seems to be there but ticket can be closed because it's not crucial )
```
th> require "optnet"
{
  removeOptimization : function: 0x41d30448
  optimizeMemory : function: 0x40595aa8
  test : function: 0x41d14c68
  countUsedMemory : function: 0x41d63d08
}
```

**Comment by liuzhuang13** [comment]
Maybe try updating/reinstalling fb.resnet.torch? There have been changes recently:)
