### ISSUE TITLE
Wide-DenseNet

### ISSUE THREAD

**Issue by 1292765944** [liuzhuang13/DenseNet#20]
Congrats  for best paper on CVPR 2017!
I'm troubled with the memory problem with densenet. Would you share your wide-densenet implementation and pre-train models publicly?

Best!

**Comment by 1292765944** [comment]
Another question is that it seems densenet do not show large improvements in accuracy compared to resnet on large scale imagenet as on CIFAR100? Am I right?

**Comment by liuzhuang13** [comment]
Hello @1292765944 and thanks! 

To run a wide-densenet just set -depth to be relatively small (e.g. 40) and -growthRate to be relatively large (e.g. 48), there's no seperate implementation for wide-densenet. 

And sorry we didn't train any wide-densenets on ImageNet, so no pre-trained models are available now.

**Comment by 1292765944** [comment]
@liuzhuang13 
You mean DenseNet-161 (k=48)? I notice that your imagenet pre-trained models all have large growthRate(32 or 48) . So wide-densenet means more wider?

**Comment by liuzhuang13** [comment]
@1292765944 Yes, probably a larger growth rate will do better, since ImageNet is such a complex dataset.
