### ISSUE TITLE
about nninit package

### ISSUE THREAD

**Issue by xichangzun** [liuzhuang13/DenseNet#25]
I ran into a bug said 'could not found nninit package', I am not sure if [this package](https://github.com/Kaixhin/nninit) is what I need.
It seems like the package is not used at all,shoud we just remove it?
And......Since the nninit package is not defaultly installed, I think the README file should mention it.

**Comment by liuzhuang13** [comment]
@xichangzun Hi, thanks for pointing out. This package is indeed not needed, so we removed it in our code. Now it should be ok.
