### ISSUE TITLE
Is error rates top-1 or top-5 in experiment result?

### ISSUE THREAD

**Issue by haikuoyao** [liuzhuang13/DenseNet#26]
Hi there,

I try to reproduce experiment result.

Sorry, this might be a silly question.
Is error rates top-1 or top-5 in this table?

<img width="770" alt="screen shot 2017-07-28 at 5 39 52 pm" src="https://user-images.githubusercontent.com/8957771/28712173-bf1820d0-73bc-11e7-9eeb-e6b0602391a8.png">

Thanks.

**Comment by taineleau** [comment]
TOP 1.

**Comment by haikuoyao** [comment]
@taineleau Thank you.
May I ask another question?
In paper, we compute the average (absolute) weight to conduct an experiment on Feature Reuse.
What is exactly the `weight`?
And how do we compute it?
Thanks a lot.

**Comment by taineleau** [comment]
@haikuoyao Let me try to answer your question. @liuzhuang13 Please correct me if I am wrong. Basically, the weight of a convolution layer is of shape `(n_input_planes, n_output_plane, filter_width, filter_height)`. If we are looking at a specific layer `l`, say `l = 3`, this layer accepts features from layer 0, 1 and 2, which are concatenated as the input to layer 3.

Suppose we store the weight in `w` (a python variable). (Note that, the number of channel of layer 0 is 24, and the growth rate `k` is `12`).
Hence, the weight for the grid (s=0, l=3) is `w[:24, :, :, :]`;
For (s=1, l=3), it's `w[24:36, :, :, :]`;
For (s=2, l=3), it's `w[36:48, :, :, :]`.

**Comment by haikuoyao** [comment]
Thanks a lot @taineleau .
Sorry to ask another question.
How long did it take to classify one single image with `densenet-161.t7` model by `classify.lua` in you guys' experiment?
It takes around 2s here on GPU. Seems it's right. It shouldn't take so long, right?

**Comment by haikuoyao** [comment]
oh... When I classified more than one image, it just took a little bit long on the first image and quite fast on rest images. Seems it's okay.
Sorry to bother you.

**Comment by taineleau** [comment]
@haikuoyao You're right. For the first batch, the chips need some more time to get prepared. I believe if you take a look at the `data time`, it takes up most of the time when you forward the first batch.

**Comment by haikuoyao** [comment]
@taineleau Thanks a lot. I'm gonna close this issue.  :)
