### ISSUE TITLE
Great results! CIFAR-100 top1 accuracy ~ 100%

### ISSUE THREAD

**Issue by pannous** [liuzhuang13/DenseNet#3]
Not a bug, just a praise: Within a few hours the CIFAR-100 accuracy goes up to 100% !
```
 | Epoch: [190][423/782]    Time 0.166  Data 0.000  Err 0.0518  top1   0.000  top5   0.000
 | Epoch: [190][424/782]    Time 0.166  Data 0.000  Err 0.1035  top1   3.125  top5   0.000
 | Epoch: [190][425/782]    Time 0.166  Data 0.000  Err 0.0389  top1   1.562  top5   0.000
```
Legendary! Time to increase the test set.

**Comment by liuzhuang13** [comment]
Thanks! But in my understanding what you showed is the training top1 error, it's not a surprise that the training error will go down to almost 0 at some point....
