### ISSUE TITLE
What is proper way of counting parameters?

### ISSUE THREAD

**Issue by Lyken17** [liuzhuang13/DenseNet#38]
Hi author, as you claimed in both repo and paper, the numer of parameters of `densenet-100-12` is **7.0M** and `densenet-100-24` is **27.72M**. However when I examine the parameters in following way

```lua
-- main.lua, line 32
-- Create model
local model, criterion = models.setup(opt, checkpoint)

params = model:getParameters()
print(#params)
```

I got **4.06M** for `densenet-100-12` and **16.11M** for `densenet-100-24`. Did I count it in a wrong way?

**Comment by liuzhuang13** [comment]
Hi, did you use the bottleneck structure? Can you show me the model definition?

**Comment by Lyken17** [comment]
No, all models are not using BC structure.

Here are the model definitions.
[40-12-no-bc.txt](https://github.com/liuzhuang13/DenseNet/files/1460588/40-12-no-bc.txt)
[100-12-no-bc.txt](https://github.com/liuzhuang13/DenseNet/files/1460589/100-12-no-bc.txt)
[100-24-no-bc.txt](https://github.com/liuzhuang13/DenseNet/files/1460590/100-24-no-bc.txt)

**Comment by liuzhuang13** [comment]
You seemed to be using reduction_rate = 0.5. In our non-BC structures, the reduction rate is 1, which means no channel reduction at transition layer.

**Comment by Lyken17** [comment]
Thank you! I see where my mistake is.
