### ISSUE TITLE
A question about network structure

### ISSUE THREAD

**Issue by linquanxu** [liuzhuang13/DenseNet#39]
Hi, I want to design a DenseNet which has the smalle number of layers.(e.g. L=30 or another). How to set each dense block and k (L denotes the network depth and k its growth rate.)? Are there any rules?

**Comment by liuzhuang13** [comment]
Hi @linquanxu , in my opinion, for a small network, the most simple rule is to make every dense block have equal number of layers and the same k, and it will probably work well.

**Comment by linquanxu** [comment]
Hi, @liuzhuang13 , thanks for your relay. I close this issue now.
