### ISSUE TITLE
is there any code for caffe?

### ISSUE THREAD

**Issue by tron19920125** [liuzhuang13/DenseNet#4]

**Comment by liuzhuang13** [comment]
Our servers' systems got reinstalled just a few days a ago, unfortunately I don't have the permission to install caffe and its dependencies, but I have the code to generate the network and solver files. I can send you the code by email but the code is not tested.

**Comment by tron19920125** [comment]
OK，Thanks a lot
2401029220@qq.com

**Comment by mananshah99** [comment]
I would appreciate if you could send the caffe network/solver files to me as well, email is manan dot shah dot 777 at gmail.com. Thanks!

**Comment by liuzhuang13** [comment]
@tron19920125  @mananshah99  Now the caffe version is online. https://github.com/liuzhuang13/DenseNetCaffe

Thanks for your interest!

**Comment by mananshah99** [comment]
👍 thank you!
