### ISSUE TITLE
What is architecture of  (L=40,k=12)  DenseNet on Cifar10

### ISSUE THREAD

**Issue by Johnson-yue** [liuzhuang13/DenseNet#45]
I will implement DenseNet on CIFAR but， I don·t know  how many dense block 。

**Comment by DanielTea** [comment]
Do a model.summary() to print the architecture.

**Comment by DanielTea** [comment]
ups sorry wrong language

**Comment by Johnson-yue** [comment]
@DanielTea Sorry，It is my fault.  In the original paper: [Densely Connected Convolutional Networks](https://arxiv.org/abs/1608.06993), it provided ImageNet architecture that shown in Table 1。 But It is not provide CIFAR model，for example, how many  DenseNet-B  block? I only know, total layers is 100 or 250 or 190

**Comment by Ouwen** [comment]
@DanielTea  For cifar10, there are 3 dense blocks. There will be 1 conv2d layer initially which is a 3x3 conv, stride 1, and 3 transition layers (4 other layers)

So for depth = 40, we take 40-4 (other layers) = 36, then we take 36/3 = 12,

So there are 12 layers in each dense block. If bottlenecks are used, then there will be 6 layers and 6 bottlenecks in each dense block.

Hope this helps!

**Comment by yuffon** [comment]
> @Johnson-yue For cifar10, there are 3 dense blocks. There will be 1 conv2d layer initially which is a 3x3 conv, stride 1, and 3 transition layers (4 other layers)
> 
> So for depth = 40, we take 40-4 (other layers) = 36, then we take 36/3 = 12,
> 
> So there are 12 layers in each dense block. If bottlenecks are used, then there will be 6 layers and 6 bottlenecks in each dense block.
> 
> Hope this helps!

what about the final linear layer?

**Comment by Johnson-yue** [comment]
@yuffon Sorry,  It is long time before,so I don't have any information about this.
