### ISSUE TITLE
DenseNet on Pascal VOC

### ISSUE THREAD

**Issue by blateyang** [liuzhuang13/DenseNet#47]
Hi, I think DenseNet is a promising model and I try to take it as the backbone of Faster R-CNN in object detection. I chose DenseNet169 pretrained on ImageNet to replace the ResNet50 backbone of Faster R-CNN and used the same hyperparameters configuration as ResNet50 version of Faster R-CNN. However, the training result of DenseNet version is worse than ResNet50 version(roughly 3% lower on VOC2012 test). Can you help me analyse the reason or give me any advice? @liuzhuang13 Many thanks!

**Comment by liuzhuang13** [comment]
We didn't tune the configs and architectures on the faster-rcnn framework. Thus we cannot guarantee the current design is good enough for that.

**Comment by blateyang** [comment]
Anyway, thanks for replying!
