### ISSUE TITLE
Why not share the first BN and ReLU?

### ISSUE THREAD

**Issue by Sunnydreamrain** [liuzhuang13/DenseNet#52]
Hi,

The features go through BN-ReLU-Conv-BN-ReLU-Conv , then concatenate the features from different layers. Since BN is applied to each channel, and ReLU applies element-wisely. Why not share the first BN-ReLU? The features go through Conv-BN-ReLU-Conv-BN-ReLU, then concatenate the output of ReLU features? Is their any difference?

Thanks.

**Comment by robertomest** [comment]
There was some discussion on this topic in [this issue](https://github.com/liuzhuang13/DenseNetCaffe/issues/2#issuecomment-250789774). By preactivating each layer has its own BatchNorm parameters which seem to improve results on deeper networks.

**Comment by Sunnydreamrain** [comment]
Okay. I see.
Thanks a lot.
