### ISSUE TITLE
Is there a pretrained CIFAR 100 or CIFAR 10 model?

### ISSUE THREAD

**Issue by Yijun88** [liuzhuang13/DenseNet#61]
Hi @liuzhuang13,

I'm trying to extend a regression model based on denseNet. Since my inputs size are expected to be very small, a pre-trained denseNet-BC (l=100, k12) is preferred. I'm wondering would you be able to provide any pre-trained model on CIFAR 100?

**Comment by liuzhuang13** [comment]
Sorry we don't have one on this repo. But many other repos do provide such models, for example, this one, https://github.com/bearpaw/pytorch-classification

**Comment by Yijun88** [comment]
Thanks for the info!
