### ISSUE TITLE
Nice figures ! 

### ISSUE THREAD

**Issue by trypag** [liuzhuang13/DenseNet#9]
Hey,
I am sorry to ask this, but your figures are really nice, I have no experience for drawing nn figure and I would like to follow your style if you let me :)
Could you please tell me what did you use to make such simple and nice looking figures ?
Thanks !

**Comment by trypag** [comment]
I am specifically by figure 1, on 1st page

**Comment by gaohuang** [comment]
It was made with Microsoft Visio :-)

**Comment by trypag** [comment]
Nice thank you !
